[package]
name = "serde"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-expand = "1.0.117"
# serde = { version = "1.0.218", feature = ["derive"] }
serde = { version = "1.0.218", features = ["derive"] }

serde_json = "1.0.145"
